# This is a TOML document. Boom.

[GooseBuild]
# 建库最多使用cpu个数.0表示设置为机器的cpu数
MaxProcs = 0

    # 建库数据库的相关配置
    [GooseBuild.DataBase]
    # 索引库的目标位置
    DbPath = "data/testdemo"
    # 正排转倒排的内存缓冲区最大容纳term数量.
    # 越大越好,减少读写磁盘数,随之内存占用越多.
    TransformMaxTermCnt = 1000000
    # 索引库最大id数
    MaxId = 5000000
    # 索引文件最大文件大小,单位(B),1G = 1073741824B
    MaxIndexFileSize = 1073741824
    # Data文件最大文件大小,单位(B),1G = 1073741824B
    MaxDataFileSize = 1073741824
    # 每个doc的Value大小,单位(B)
    ValueSize = 32

[Strategy]
    # 建库策略
    [Strategy.Indexer]
        [Strategy.Indexer.Scws]
        xdbdict = "dict/dict.utf8.xdb"
        rules = "dict/rules.utf8.ini"
    # 检索策略
    [Strategy.Searcher]
        [Strategy.Indexer.Scws]
        xdbdict = "dict/dict.utf8.xdb"
        rules = "dict/rules.utf8.ini"

